# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/l01k/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/l01k

PRODUCT_COPY_FILES += \
    vendor/lge/l01k/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/lge/l01k/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/lge/l01k/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    vendor/lge/l01k/proprietary/vendor/firmware/cxd224x_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cxd224x_firmware.bin
